name = "ai-stats-gateway"
main = "src/index.ts"
compatibility_date = "2025-10-01"
compatibility_flags = []
workers_dev = false
preview_urls = false

[vars]
ENV = "prod"
SUPABASE_URL = "https://xansbgjaduxypzsmjwct.supabase.co"

[placement]
mode = "smart"

[[routes]]
pattern = "api.phaseo.app"
custom_domain = true

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[[kv_namespaces]]
binding = "GATEWAY_CACHE"
id = "f5e23068fcd94125ad9860c817c543d9"
preview_id = "f5e23068fcd94125ad9860c817c543d9"
